### ISSUE TITLE
Can't generate RSQL to filter by empty string

### ISSUE THREAD

**Issue by PoffM** [molgenis/molgenis-js-rsql#10]
Hello,
I want to filter by empty-string values, but the object I would expect converts to this filter actually generates invalid RSQL according to my back-end (which uses https://github.com/jirutka/rsql-parser)

### How to Reproduce
```javascript
import { transformToRSQL } from "@molgenis/rsql";

console.log(
  transformToRSQL({
    arguments: "",
    comparison: "==",
    selector: "description"
  })
);
```

### Expected behavior
```
description==''
```

### Observed behavior
This code produces:
```
description==
```
which my back-end fails to parse:

```
cz.jirutka.rsql.parser.RSQLParserException: cz.jirutka.rsql.parser.ParseException: Encountered "<EOF>" at line 1, column 17.
Was expecting one of:
    <UNRESERVED_STR> ...
    <SINGLE_QUOTED_STR> ...
    <DOUBLE_QUOTED_STR> ...
    "(" ...
```

**Comment by fdlk** [comment]
As a workaround, I think you can use `arguments: "''"` but I agree that this should work as well.

**Comment by PoffM** [comment]
Using:

```javascript
transformToRSQL({
  arguments: "''",
  comparison: "==",
  selector: "description"
})
```

Unfortunately I get:

```
description=="''"
```

which filters by values with apostrophes.
